version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth_service
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo1

  products:
    build:
      context: .
      dockerfile: apps/products/Dockerfile
    container_name: products_service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo1

  orders:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
    container_name: orders_service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo1

  ecommerce-app:
    build:
      context: .
      dockerfile: apps/ecommerce-app/Dockerfile
    container_name: ecommerce_gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - auth
      - products
      - orders

  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-mongo.sh"]

volumes:
  mongo1_data: