version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth_service
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - rabbitmq
      - mongo1
      - redis

  products:
    build:
      context: .
      dockerfile: apps/products/Dockerfile
    container_name: products_service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - rabbitmq
      - mongo1
      - redis

  orders:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
    container_name: orders_service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo1
      - rabbitmq
      - redis

  ecommerce-app:
    build:
      context: .
      dockerfile: apps/ecommerce-app/Dockerfile
    container_name: ecommerce_gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_URI: mongodb://mongo1:27017/?replicaSet=rs0
      SECRET_KEY: ${SECRET_KEY}
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}

    depends_on:
      - auth
      - products
      - orders
      - rabbitmq
      - redis

  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-mongo.sh"]

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo1_data:
  rabbitmq_data:
